const cfg=window.NVEC_CONFIG;const sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const $=s=>document.querySelector(s);let user=null,profile=null,currentCourse=null;
const adult=[['메인교재 30번 듣기','메인교재를 충분히 듣고 30회 완료를 기록합니다.','listen',30],['메인교재 30번 말하기','30번 반복 연습 후 최종 녹음본을 제출합니다.','recording',30],['교정문장 10번 녹음하기','교정받은 문장을 10번 연습 후 최종 녹음합니다.','recording',10]];
const teen=[['메인교재 3번 녹음','본문을 소리 내어 3번 녹음합니다.','recording',3],['메인교재 단어 3번 녹음','메인교재 단어 전체를 3번 녹음합니다.','recording',3],['원서 3번 녹음','오늘의 원서를 소리 내어 3번 녹음합니다.','recording',3],['NVOCA 3번 녹음','오늘의 NVOCA를 3번 녹음합니다.','recording',3]];
function show(id){['loginView','courseView','missionView'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));$('#logoutBtn').classList.toggle('hidden',id==='loginView')}
function emailFor(id){return id.toLowerCase()==='admin'?'rke8096@naver.com':id.toLowerCase()+'@members.nvec.local'}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='로그인 중...';const id=$('#memberId').value.trim(),password=$('#password').value;const {data,error}=await sb.auth.signInWithPassword({email:emailFor(id),password});if(error){$('#loginMsg').textContent='아이디 또는 비밀번호를 확인해 주세요.';return}user=data.user;const {data:p,error:profileError}=await sb.from('members').select('member_id,name,role,is_active').eq('id',user.id).maybeSingle();if(profileError){$('#loginMsg').textContent='회원정보 조회 오류: '+profileError.message;return}if(!p){$('#loginMsg').textContent='로그인은 성공했지만 회원정보가 연결되지 않았습니다. UID: '+user.id;return}if(!p.is_active){await sb.auth.signOut();$('#loginMsg').textContent='현재 비활성 회원입니다.';return}profile=p;$('#loginMsg').textContent='';show('courseView')};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();user=profile=null;show('loginView')};$('#backBtn').onclick=()=>show('courseView');
document.querySelectorAll('.course-card').forEach(b=>b.onclick=()=>openCourse(b.dataset.course));
function openCourse(c){currentCourse=c;$('#missionTitle').textContent=c==='adult'?'성인과정':'초·중·고 과정';$('#today').textContent=new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'});render(c==='adult'?adult:teen);show('missionView')}
async function render(list){const box=$('#missions');box.innerHTML='';const d=new Date();d.setHours(0,0,0,0);const {data:rows}=await sb.from('learning_records').select('mission,record_type,audio_path,repetition,completed_at').eq('user_id',user.id).eq('course',currentCourse).gte('completed_at',d.toISOString());list.forEach((m,i)=>{const saved=(rows||[]).filter(r=>r.mission===m[0]),count=m[2]==='recording'?saved.filter(r=>r.record_type==='recording').length:saved.length,el=document.createElement('article');el.className='mission'+(count>=m[3]?' done':'');el.innerHTML='<span class="num">MISSION '+String(i+1).padStart(2,'0')+'</span><h3>'+m[0]+'</h3><p>'+m[1]+'</p><div class="mission-progress"><b class="count">'+Math.min(count,m[3])+' / '+m[3]+'</b></div><div class="record-tools"></div>';m[2]==='recording'?setupRecorder(el,el.querySelector('.record-tools'),m,count):setupCounter(el,el.querySelector('.record-tools'),m,count);box.appendChild(el)});updateProgress()}
function setupCounter(el,tools,m,count){const b=document.createElement('button');b.textContent=count>=m[3]?'학습기록 저장 완료 ✓':'오늘 30번 듣기 완료';b.disabled=count>=m[3];b.onclick=async()=>{b.disabled=true;const {error}=await sb.from('learning_records').insert({user_id:user.id,course:currentCourse,mission:m[0],record_type:'listen',repetition:m[3]});if(error){alert('저장하지 못했습니다: '+error.message);b.disabled=false;return}el.classList.add('done');el.querySelector('.count').textContent=m[3]+' / '+m[3];b.textContent='학습기록 저장 완료 ✓';updateProgress()};tools.appendChild(b)}
function setupRecorder(el,tools,m,count){const status=document.createElement('p');status.className='rec-status';status.textContent=count>=m[3]?'목표 녹음 완료':'녹음 준비';const start=document.createElement('button');start.textContent=count>=m[3]?'학습기록 저장 완료 ✓':'● 녹음 시작';start.disabled=count>=m[3];const stop=document.createElement('button');stop.textContent='■ 녹음 종료';stop.disabled=true;stop.className='secondary-btn';const audio=document.createElement('audio');audio.controls=true;audio.className='hidden recording-player';const save=document.createElement('button');save.textContent='이 녹음 저장';save.className='hidden save-recording';let recorder,chunks=[],blob=null,stream=null;start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});audio.src=URL.createObjectURL(blob);audio.classList.remove('hidden');save.classList.remove('hidden');status.textContent='녹음을 들어보고 저장하세요.';stream.getTracks().forEach(t=>t.stop())};recorder.start();start.disabled=true;stop.disabled=false;status.textContent='녹음 중...'}catch(e){status.textContent='마이크 권한이 필요합니다.';start.disabled=false}};stop.onclick=()=>{if(recorder&&recorder.state!=='inactive'){recorder.stop();stop.disabled=true}};save.onclick=async()=>{if(!blob)return;save.disabled=true;status.textContent='저장 중...';const ext=blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm',safe=m[0].replace(/[^0-9A-Za-z가-힣_-]/g,'_'),path=user.id+'/'+new Date().toISOString().slice(0,10)+'/'+safe+'-'+Date.now()+'.'+ext;const {error:upErr}=await sb.storage.from('recordings').upload(path,blob,{contentType:blob.type||'audio/webm'});if(upErr){status.textContent='녹음 파일 저장 실패: '+upErr.message;save.disabled=false;return}const next=count+1;const {error:dbErr}=await sb.from('learning_records').insert({user_id:user.id,course:currentCourse,mission:m[0],record_type:'recording',audio_path:path,repetition:next});if(dbErr){status.textContent='학습기록 저장 실패: '+dbErr.message;save.disabled=false;return}count=next;el.querySelector('.count').textContent=Math.min(count,m[3])+' / '+m[3];blob=null;audio.classList.add('hidden');save.classList.add('hidden');if(count>=m[3]){el.classList.add('done');start.textContent='학습기록 저장 완료 ✓';start.disabled=true;status.textContent='목표 녹음 완료'}else{start.disabled=false;start.textContent='● 다음 녹음 시작';status.textContent=count+'회 저장 완료 · '+(m[3]-count)+'회 남음'}save.disabled=false;updateProgress()};tools.append(status,start,stop,audio,save)}
function updateProgress(){const all=[...document.querySelectorAll('.mission')],done=all.filter(x=>x.classList.contains('done')).length,p=all.length?Math.round(done/all.length*100):0;$('#progressText').textContent=p+'%';$('#progressBar').style.width=p+'%'}
(async()=>{const {data:{session}}=await sb.auth.getSession();if(!session)return;user=session.user;const {data:p}=await sb.from('members').select('member_id,name,role,is_active').eq('id',user.id).single();if(p&&p.is_active){profile=p;show('courseView')}})();