const cfg=window.NVEC_CONFIG;const sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const $=s=>document.querySelector(s);let user=null,profile=null,currentCourse=null;
const adult=[['메인교재 30번 듣기','메인교재를 충분히 듣고 30회 완료를 기록합니다.','listen',30],['메인교재 30번 말하기','30번 반복 연습 후 최종 녹음본을 제출합니다.','recording',30],['교정문장 10번 녹음하기','교정받은 문장을 10번 연습 후 최종 녹음합니다.','recording',10]];
const teen=[['메인교재 3번 녹음','본문을 소리 내어 3번 녹음합니다.','recording',3],['메인교재 단어 3번 녹음','메인교재 단어 전체를 3번 녹음합니다.','recording',3],['원서 3번 녹음','오늘의 원서를 소리 내어 3번 녹음합니다.','recording',3],['NVOCA 3번 녹음','오늘의 NVOCA를 3번 녹음합니다.','recording',3]];
function show(id){['loginView','courseView','missionView'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));$('#logoutBtn').classList.toggle('hidden',id==='loginView')}
function emailFor(id){return id.toLowerCase()==='admin'?'rke8096@naver.com':id.toLowerCase()+'@members.nvec.local'}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='로그인 중...';const id=$('#memberId').value.trim(),password=$('#password').value;const {data,error}=await sb.auth.signInWithPassword({email:emailFor(id),password});if(error){$('#loginMsg').textContent='아이디 또는 비밀번호를 확인해 주세요.';return}user=data.user;const {data:p,error:profileError}=await sb.from('members').select('member_id,name,role,is_active').eq('id',user.id).maybeSingle();if(profileError){$('#loginMsg').textContent='회원정보 조회 오류: '+profileError.message;return}if(!p){$('#loginMsg').textContent='로그인은 성공했지만 회원정보가 연결되지 않았습니다. UID: '+user.id;return}if(!p.is_active){await sb.auth.signOut();$('#loginMsg').textContent='현재 비활성 회원입니다.';return}profile=p;$('#loginMsg').textContent='';show('courseView')};
$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();user=profile=null;show('loginView')};$('#backBtn').onclick=()=>show('courseView');
document.querySelectorAll('.course-card').forEach(b=>b.onclick=()=>openCourse(b.dataset.course));
function openCourse(c){currentCourse=c;$('#missionTitle').textContent=c==='adult'?'성인과정':'초·중·고 과정';$('#today').textContent=new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'});render(c==='adult'?adult:teen);show('missionView')}
async function render(list){const box=$('#missions');box.innerHTML='';list.forEach((m,i)=>{const el=document.createElement('article');el.className='mission';el.innerHTML='<span class="num">MISSION '+String(i+1).padStart(2,'0')+'</span><h3>'+m[0]+'</h3><p>'+m[1]+'</p><button>학습 완료 기록</button>';el.querySelector('button').onclick=()=>complete(el,m);box.appendChild(el)});updateProgress()}
async function complete(el,m){if(!user)return;const btn=el.querySelector('button');btn.disabled=true;const {error}=await sb.from('learning_records').insert({user_id:user.id,course:currentCourse,mission:m[0],record_type:m[2]==='recording'?'complete':m[2],repetition:m[3]});if(error){alert('저장하지 못했습니다. 잠시 후 다시 시도해 주세요.');btn.disabled=false;return}el.classList.add('done');btn.textContent='학습기록 저장 완료 ✓';updateProgress()}
function updateProgress(){const all=[...document.querySelectorAll('.mission')],done=all.filter(x=>x.classList.contains('done')).length,p=all.length?Math.round(done/all.length*100):0;$('#progressText').textContent=p+'%';$('#progressBar').style.width=p+'%'}
(async()=>{const {data:{session}}=await sb.auth.getSession();if(!session)return;user=session.user;const {data:p}=await sb.from('members').select('member_id,name,role,is_active').eq('id',user.id).single();if(p&&p.is_active){profile=p;$('#memberName').textContent=p.name;show('courseView')}})();